### ISSUE TITLE
Fails to login with snac2 instances.

### ISSUE THREAD

**Issue by dhrm1k** [ihabunek/toot#523]
i run a [snac2](https://codeberg.org/grunfink/snac2) instance at linuxusers.in but whenever for logging in, i enter my instance it returns instance not found.

i also checked entering other instances to see if it's not just my instance. tried with [snac.bsd.cafe](https://snac.bsd.cafe/).

i have been trying to understand what's wrong, but haven't been able to.

**Comment by dhrm1k** [comment]
yes, same. i couldn't figure out what the error was. made a new tool then to post to snac and view posts from command line. a lot of things don't work. open to any new features you want or any feedback.

https://github.com/dhrm1k/snac.py

**Comment by ihabunek** [comment]
The problem here is that the snac server returns differently formatted datetimes so datetime parsing fails.

Additionally, I have a bug that this error is not displayed.

Working on a fix. We'll see what other problems we run into since I've never tested toot on snac2.

**Comment by ihabunek** [comment]
This should be fixed in [0.48.0](https://github.com/ihabunek/toot/releases/tag/0.48.0), please test.

Does snac2 support registration via web? I installed it locally and started with docker, but wasn't able to run the test suite because it requires that registrations are open and don't require the email to be verified.

**Comment by dhrm1k** [comment]
no it doesn't support registration through web. but i just tested it on my snac instance and it works.

https://linuxusers.in/dharmik/p/1741255915.692667

**Comment by dhrm1k** [comment]
edit: i tried to change timeline to my personal timeline and it returned me account not found. so there's no way for me to edit this too. if you want an account on my instance. let me know. i can get you one instantly right now. i am on computer rn so.

**Comment by ihabunek** [comment]
I can reproduce this locally. I'll look into it.

**Comment by ihabunek** [comment]
The problem is that searching for users doesn't return any results. E.g.:

```
λ toot --debug search testuser --json
DEBUG:toot: --> GET http://localhost:8001/api/v2/search?q=testuser&resolve=false&type=accounts
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:8001
DEBUG:urllib3.connectionpool:http://localhost:8001 "GET /api/v2/search?q=testuser&resolve=false&type=accounts HTTP/1.1" 200 77
DEBUG:toot: <-- GET http://localhost:8001/api/v2/search?q=testuser&resolve=false&type=accounts HTTP 200 1ms
{
    "accounts": [
    ],
    "statuses": [
    ],
    "hashtags": [
    ]
}
```

This should return the `testuser` account since it exists locally. Maybe snac2 does not implement searching?

I can work around it for loading the personal timeline, but it may fail in other places where search is required.

**Comment by ihabunek** [comment]
OK, personal timeline should work in 0.48.1

**Comment by ihabunek** [comment]
Closing issue, open new ones if you find new problems.
