### ISSUE TITLE
Unrecognised color specification 'italics' in foreground

### ISSUE THREAD

**Issue by noffle** [ihabunek/toot#162]
I get this output when I run `toot tui`:

```
Traceback (most recent call last):
  File "/usr/bin/toot", line 11, in <module>
    load_entry_point('toot==0.25.2', 'console_scripts', 'toot')()
  File "/usr/lib/python3/dist-packages/toot/console.py", line 545, in main
    run_command(app, user, command_name, args)
  File "/usr/lib/python3/dist-packages/toot/console.py", line 527, in run_command
    return fn(app, user, parsed_args)
  File "/usr/lib/python3/dist-packages/toot/commands.py", line 331, in tui
    TUI.create(app, user).run()
  File "/usr/lib/python3/dist-packages/toot/tui/app.py", line 82, in create
    unhandled_input=tui.unhandled_input,
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 114, in __init__
    screen.register_palette(palette)
  File "/usr/lib/python3/dist-packages/urwid/display_common.py", line 785, in register_palette
    self.register_palette_entry(*item)
  File "/usr/lib/python3/dist-packages/urwid/display_common.py", line 852, in register_palette_entry
    basic = AttrSpec(foreground, background, 16)
  File "/usr/lib/python3/dist-packages/urwid/display_common.py", line 489, in __init__
    self.foreground = fg
  File "/usr/lib/python3/dist-packages/urwid/display_common.py", line 578, in _set_foreground
    "in foreground (%s)") % (repr(part), repr(foreground)))
urwid.display_common.AttrSpecError: Unrecognised color specification 'italics' in foreground (',italics')
```

Running Debian 9.4. Seems like it might be the same issue as #124?

**Comment by ihabunek** [comment]
How did you install toot? If via apt-get, my guess is that Debian 9.4 has an older version of Urwid. Urwid 2.0.x is required.

I will probably be removing the [APT package repository](https://toot.readthedocs.io/en/latest/install.html#apt-package-repository), turns out it causes more problems than it solves, and leave the packaging to people who know what they're doing.

**Comment by noffle** [comment]
Yes, via the apt instructions.

I tried to install via `pip3 install toot` and running the tui gives ![toot](https://user-images.githubusercontent.com/489362/79305641-a40ad400-7ea8-11ea-8eae-6935cded97c9.png)

I tried removing that and used `pip install toot` instead, but running `toot tui` gives
```
Traceback (most recent call last):
  File "/home/sww/.local/bin/toot", line 7, in <module>
    from toot.console import main
  File "/home/sww/.local/lib/python2.7/site-packages/toot/console.py", line 5, in <module>
    import logging
  File "/home/sww/.local/lib/python2.7/site-packages/toot/logging.py", line 1, in <module>
    from logging import getLogger
ImportError: cannot import name getLogger
```

**Comment by noffle** [comment]
@ihabunek thank you for taking the time to help :green_heart:

**Comment by ihabunek** [comment]
toot will not work on python 2.7 (using pip). It should work on 3.5 (using pip3). I'll look into the error.

**Comment by ihabunek** [comment]
Okay, found the problem in [`datetime.astimezone()`](https://docs.python.org/3/library/datetime.html#datetime.datetime.astimezone). I'm depending on behaviour introduced in python 3.6, and you're using pyhton 3.5:

> Changed in version 3.6: The astimezone() method can now be called on naive instances that are presumed to represent system local time.

I'll fix this.

**Comment by ihabunek** [comment]
@noffle Could you update to 0.26.0 and check if it works now?

**Comment by noffle** [comment]
@ihabunek it works! I really appreciate all of your help getting this working :green_heart:
